language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0.0
notifications:
  email: false
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Cbc"); Pkg.test("Cbc"; coverage=true)'
#after_success:
    #- julia -e 'cd(Pkg.dir("Cbc")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
