language: julia
branches:
  only:
    - master
    - /^release-.*$/
notifications:
  email: false
codecov: true
jobs:
  include:
    - os: linux
      arch: x64
      julia: 1
    - os: linux
      arch: x64
      julia: 1.0
    - os: linux
      arch: x86
      julia: 1.0
    - os: osx
      arch: x64
      julia: 1
